# Generated by Django 2.0.5 on 2018-05-30 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('telephone', models.IntegerField(verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Description')),
                ('picture', models.ImageField(upload_to='', verbose_name='Picture')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
