# Generated by Django 2.0 on 2018-06-08 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField(verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Physical Address')),
                ('description', models.TextField(verbose_name='Description')),
                ('picture', models.ImageField(upload_to='media\\agent', verbose_name='Picture')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
