# Generated by Django 2.0 on 2018-06-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.ImageField(upload_to='agent', verbose_name='Picture'),
        ),
    ]
