# Generated by Django 2.0.5 on 2018-05-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='email',
        ),
        migrations.AddField(
            model_name='agent',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Physical Address'),
        ),
    ]
