# Generated by Django 2.0.5 on 2018-05-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20180531_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='name',
        ),
    ]
