# Generated by Django 2.0.5 on 2018-06-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.ImageField(upload_to='media/agent/<function now at 0x7f2dfca70620>', verbose_name='Picture'),
        ),
    ]
