# Generated by Django 2.0.5 on 2018-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_auto_20180602_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='picture',
            field=models.ImageField(upload_to='media/agent', verbose_name='Picture'),
        ),
    ]
