# Generated by Django 2.0.5 on 2018-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='property/2018-05-31 14:49:51.437613+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:49:51.437653+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:49:51.437678+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:49:51.437698+00:00'),
        ),
    ]
