# Generated by Django 2.0 on 2018-06-09 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyenquiry',
            options={'ordering': ['date', 'property'], 'verbose_name': 'Property Inquiry', 'verbose_name_plural': 'Property Inquiries'},
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='telephone',
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='subject',
            field=models.CharField(default='Subject default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='C:\\Users\\jerry\\PycharmProjects\\real_estate\\media\\property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\jerry\\PycharmProjects\\real_estate\\media\\property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\jerry\\PycharmProjects\\real_estate\\media\\property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\jerry\\PycharmProjects\\real_estate\\media\\property'),
        ),
    ]
