# Generated by Django 2.0.5 on 2018-05-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20180531_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='property/2018-05-31 14:53:29.645214+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:53:29.645255+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:53:29.645280+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(null=True, upload_to='property/2018-05-31 14:53:29.645302+00:00'),
        ),
    ]
