# Generated by Django 2.0.5 on 2018-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20180531_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='description',
            field=models.TextField(default='good field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='property/2018-05-31 15:03:49.431001+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:03:49.431042+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:03:49.431067+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:03:49.431088+00:00'),
        ),
    ]
