# Generated by Django 2.0.5 on 2018-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20180531_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Property test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_1',
            field=models.ImageField(upload_to='property/2018-05-31 15:06:49.772324+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_2',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:06:49.772366+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_3',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:06:49.772391+00:00'),
        ),
        migrations.AlterField(
            model_name='property',
            name='picture_4',
            field=models.ImageField(blank=True, null=True, upload_to='property/2018-05-31 15:06:49.772413+00:00'),
        ),
    ]
