# Generated by Django 2.0.5 on 2018-06-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20180602_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
