# Generated by Django 2.0.5 on 2018-06-02 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer E-Mail')),
                ('telephone', models.IntegerField(verbose_name='Customer Telephone')),
                ('message', models.TextField(verbose_name='Customer Message')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Property', verbose_name='Property Details')),
            ],
        ),
    ]
